#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# Generates the ./secrets/ folder used by docker-compose (top-level "secrets:").
# To be run ONCE from the project root (where docker-compose.yml is located).
#
# Why a script rather than commands typed by hand:
# - avoids the generated values ending up in the shell history (~/.bash_history)
# - guarantees restrictive permissions from the moment of creation (no window
#   where the file is world-readable before a corrective chmod)
# -----------------------------------------------------------------------------
set -euo pipefail

SECRETS_DIR="./secrets"
mkdir -p "$SECRETS_DIR"
chmod 700 "$SECRETS_DIR"

generate_random_secret() {
    local target_file="$1"
    if [ -f "$target_file" ]; then
        echo "  -> $target_file existe déjà, on ne l'écrase pas (utilise --force pour régénérer)."
        return
    fi
    # 32 raw random bytes -> exactly the size expected by oauth2-proxy
    # (16, 24, or 32 bytes after decoding) for cookie_secret.
    umask 077
    openssl rand -base64 32 | tr -d '\n' > "$target_file"
    chmod 600 "$target_file"
    echo "  -> $target_file généré (600)."
}

prompt_secret() {
    local label="$1"
    local target_file="$2"
    if [ -f "$target_file" ]; then
        echo "  -> $target_file existe déjà, on ne l'écrase pas (utilise --force pour ressaisir)."
        return
    fi
    umask 077
    read -rsp "  Colle la valeur pour [$label] (rien ne s'affiche à l'écran) : " value
    echo
    printf '%s' "$value" > "$target_file"
    chmod 600 "$target_file"
    echo "  -> $target_file écrit (600)."
}

# -----------------------------------------------------------------------------
# Shared gateway secret (audit 3.7): known only to Traefik and to `app`.
# Traefik injects it (overwriting any client-supplied value) on every
# request routed to `app` via a dynamic configuration file; `app`
# verifies it before any processing. Prevents a neighboring container
# on the same Docker network from joining `app` directly, outside
# Traefik, and forging X-Auth-Request-Email. The value must be
# IDENTICAL on both sides: it is generated once into the Docker
# secret, then the Traefik dynamic file is rendered from that same
# value.
GATEWAY_DYNAMIC_FILE="./traefik/dynamic/gateway-secret.yml"

render_gateway_dynamic() {
    local secret_file="$1"
    local value
    value="$(cat "$secret_file")"
    mkdir -p "$(dirname "$GATEWAY_DYNAMIC_FILE")"
    umask 077
    cat > "$GATEWAY_DYNAMIC_FILE" <<EOF
# File GENERATED by generate-secrets.sh — DO NOT COMMIT (gitignored).
# Contains the shared gateway secret (audit 3.7) in clear text. Traefik
# injects it on every request routed to \`app\` (gateway-secret@file
# middleware, referenced by the app/app-upload/app-preview/app-metrics
# routers), overwriting any client-supplied value. Must match EXACTLY
# $secret_file (same value, generated at the same time). Regenerate
# BOTH together via this script after any rotation.
http:
  middlewares:
    gateway-secret:
      headers:
        customRequestHeaders:
          X-Internal-Gateway-Secret: "$value"
EOF
    chmod 600 "$GATEWAY_DYNAMIC_FILE"
    echo "  -> $GATEWAY_DYNAMIC_FILE rendu (600) à partir de $secret_file."
}

echo "== Secrets générés automatiquement =="
generate_random_secret "$SECRETS_DIR/oauth2_cookie_secret.txt"
generate_random_secret "$SECRETS_DIR/gateway_secret.txt"
render_gateway_dynamic "$SECRETS_DIR/gateway_secret.txt"

echo
echo "== Secrets à saisir manuellement (valeurs existantes, ex: client secret Keycloak/Entra) =="
echo "⚠️  Si ces valeurs ont déjà circulé en clair ailleurs (chat, .env commité, capture d'écran),"
echo "    considère-les comme compromises : régénère un NOUVEAU secret côté Keycloak/Entra"
echo "    avant de le coller ici, plutôt que de recopier l'ancien."
prompt_secret "OAUTH2_PROXY_CLIENT_SECRET (client OIDC)" "$SECRETS_DIR/oauth2_client_secret.txt"
prompt_secret "Mot de passe admin Keycloak (lab uniquement)" "$SECRETS_DIR/keycloak_admin_password.txt"

echo
echo "Terminé. Contenu de $SECRETS_DIR :"
ls -la "$SECRETS_DIR"
echo
echo "Rappel : ajoute '$SECRETS_DIR/' à .gitignore si ce n'est pas déjà fait (voir gitignore-additions.txt)."
